import Link from 'next/link';
import PageHero from '@/components/PageHero';
import SectionTitle from '@/components/SectionTitle';
import { stats } from '@/lib/data';

export const metadata = { title: 'About | The Hope Project' };

const values=[['Compassion','We treat every child and family with dignity, empathy and respect.'],['Integrity','We are transparent with supporters, partners and the communities we serve.'],['Partnership','We build with communities, not for them, so solutions can last.'],['Impact','We focus on practical programs and measurable improvements in daily life.']];
const team=[
  ['Aisha Karim','Executive Director','https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=600&q=80'],
  ['Farhan Rahman','Programs Lead','https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=600&q=80'],
  ['Nadia Chowdhury','Community Partnerships','https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80']
];

export default function AboutPage(){ return <>
  <PageHero title="About The Hope Project" subtitle="A community-first charity working so every child can grow up healthy, educated, safe and hopeful." image="https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?auto=format&fit=crop&w=1800&q=85"/>
  <section className="section-pad"><div className="container-site grid gap-12 lg:grid-cols-2 lg:items-center"><div><p className="text-[10px] font-bold tracking-[.25em] text-black/40">OUR STORY</p><h2 className="mt-3 text-4xl font-bold">Small acts. Lasting change.</h2><p className="mt-5 leading-7 text-black/65">The Hope Project began with a simple belief: children thrive when communities have the tools to care for them. What started as a small volunteer effort grew into a network of local partnerships supporting education, nutrition, health and safe water.</p><p className="mt-4 leading-7 text-black/65">Today, we continue to work side by side with families, teachers, health workers and community leaders to build solutions that are practical, respectful and sustainable.</p></div><img src="https://images.unsplash.com/photo-1559027615-cd4628902d4a?auto=format&fit=crop&w=1300&q=85" alt="The Hope Project community team" className="h-[430px] w-full object-cover"/></div></section>
  <section className="bg-cream py-16"><div className="container-site grid gap-6 md:grid-cols-2"><div className="bg-white p-8"><p className="text-xs font-bold tracking-[.2em] text-gold">OUR MISSION</p><h3 className="mt-3 text-3xl font-bold">Help every child access the essentials for a brighter future.</h3></div><div className="bg-forest p-8 text-white"><p className="text-xs font-bold tracking-[.2em] text-gold">OUR VISION</p><h3 className="mt-3 text-3xl font-bold">A world where opportunity is not determined by where a child is born.</h3></div></div></section>
  <section className="section-pad"><div className="container-site"><SectionTitle eyebrow="WHAT GUIDES US" title="Our Values"/><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{values.map(([t,d],i)=><div key={t} className="border border-black/10 p-6"><div className="text-3xl font-bold text-gold">0{i+1}</div><h3 className="mt-4 text-xl font-bold">{t}</h3><p className="mt-2 text-sm leading-6 text-black/60">{d}</p></div>)}</div></div></section>
  <section className="bg-[#f7f8f6] py-12"><div className="container-site grid grid-cols-2 gap-y-8 md:grid-cols-4">{stats.map(s=><div className="text-center" key={s.label}><div className="text-4xl font-bold font-display">{s.value}</div><div className="mt-1 text-sm text-black/50">{s.label}</div></div>)}</div></section>
  <section className="section-pad"><div className="container-site"><SectionTitle eyebrow="PEOPLE BEHIND THE WORK" title="Meet Our Team"/><div className="mt-10 grid gap-6 md:grid-cols-3">{team.map(([n,r,img])=><div className="group" key={n}><div className="h-80 overflow-hidden"><img src={img} alt={n} className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/></div><h3 className="mt-4 text-xl font-bold">{n}</h3><p className="text-sm text-black/50">{r}</p></div>)}</div></div></section>
  <section className="border-t border-black/5 py-12"><div className="container-site"><h3 className="text-center text-2xl font-bold">Our Partners & Supporters</h3><div className="mt-8 grid grid-cols-2 items-center gap-6 text-center text-lg font-bold text-black/35 sm:grid-cols-3 lg:grid-cols-6"><span>UNICEF</span><span>WFP</span><span>WHO</span><span>Save the Children</span><span>WaterAid</span><span>CARITAS</span></div></div></section>
  <section className="bg-forest py-14 text-white"><div className="container-site flex flex-col gap-6 md:flex-row md:items-center md:justify-between"><div><h2 className="text-4xl font-bold">Be part of the next chapter.</h2><p className="mt-2 text-white/70">Volunteer, donate or share our work with someone who cares.</p></div><div className="flex flex-wrap gap-3"><Link href="/volunteer" className="btn-outline-light">Volunteer</Link><Link href="/donate" className="btn-primary">Donate Now</Link></div></div></section>
</> }
